devices:
  - name: MD880_1
    model: MD880
    enabled: true
  - name: MD880_2
    model: MD880
    enabled: true
  - name: MD880_3
    model: MD880
    enabled: true
  - name: MD880_4
    model: MD880
    enabled: false
  - name: MD880_5
    model: MD880
    enabled: true
  - name: MD880_6
    model: MD880
    enabled: true
  - name: MD880_7
    model: MD880
    enabled: true
  - name: MD880_8
    model: MD880
    enabled: true
  - name: MD880_9
    model: MD880
    enabled: true
  - name: MD880_10
    model: MD880
    enabled: true
  - name: MD880_11
    model: MD880
    enabled: true
  - name: MD880_12
    model: MD880
    enabled: true
  - name: MD880_13
    model: MD880
    enabled: true
  - name: MD880_14
    model: MD880
    enabled: true
  - name: MD880_15
    model: MD880
    enabled: true
  - name: MD880_16
    model: MD880
    enabled: true
channels:
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_1
    parameter: U5-05
    scale: 0.1
    unit: V
    signed: false
    warning_low: 450.0
    warning_high: 650.0
    alarm_low: 400.0
    alarm_high: 700.0
  - name: Detected module temperature
    tag: module_temperature
    parameter: U5-07
    scale: 0.1
    unit: C
    signed: false
    warning_low: -100.0
    warning_high: 100.0
    alarm_low: -200.0
    alarm_high: 200.0
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_3
    parameter: U15-23
    scale: 0.1
    unit: V
    signed: false
    warning_low: 1.0
    warning_high: 30.0
    alarm_low: 0.0
    alarm_high: 355.0
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_4
    parameter: U5-05
    scale: 0.1
    unit: V
    signed: false
    warning_low: 450.0
    warning_high: 650.0
    alarm_low: 400.0
    alarm_high: 700.0
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_5
    parameter: U5-05
    scale: 0.1
    unit: V
    signed: false
    warning_low: 450.0
    warning_high: 650.0
    alarm_low: 400.0
    alarm_high: 700.0
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_6
    parameter: U5-05
    scale: 0.1
    unit: V
    signed: false
    warning_low: 450.0
    warning_high: 650.0
    alarm_low: 400.0
    alarm_high: 700.0
  - name: DC bus voltage filter
    tag: DC_BUS_VOLTAGE_FILTER_7
    parameter: U5-05
    scale: 0.1
    unit: V
    signed: false
    warning_low: 450.0
    warning_high: 650.0
    alarm_low: 400.0
    alarm_high: 700.0
  - name: Beta current
    tag: BETA_CURRENT
    parameter: U6-63
    scale: 1.0
    unit: A
    signed: true
    warning_low: -20.0
    warning_high: 20.0
    alarm_low: -35.0
    alarm_high: 35.0
